---
- name: update all packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: ensure dependencies are installed
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - unattended-upgrades
      - byobu
      - fail2ban

- name: ensure unattended-upgrades is configured
  shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades

- name: ensure unattended-upgrades is enabled
  systemd:
    name: unattended-upgrades
    state: started
    enabled: yes

- name: ensure fail2ban is enabled
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: ensure /root/.vimrc is there
  copy:
    src: "../templates/root/.vimrc"
    dest: /root/.vimrc
