version: '3'
services:

  web:
    build: "web"
    ports:
      - "80"
      - "443"
    volumes:
      - /opt/app_data/web/logs:/var/log/nginx
      - "/etc/letsencrypt/live/${FRONTEND_DOMAIN}:/etc/letsencrypt/live/${FRONTEND_DOMAIN}"
    environment:
      - FRONTEND_DOMAIN=$FRONTEND_DOMAIN
      - BACKEND_DOMAIN=$BACKEND_DOMAIN

  frontend:
    build: "frontend"
    ports:
      - "3000:3000"

  db:
    image: "postgres:12"