version: "3"
services:
  web:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_WEB=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - DATABASE_URI={{ database_uri }}
      - COOKIE_FERNET_KEY={{ cookie_fernet_key }}
      - STRIPE_PUBLISHABLE_KEY={{ stripe_publishable_key }}
      - STRIPE_SECRET_KEY={{ stripe_secret_key }}
      - MAINTENANCE_SECRET={{ maintenance_secret }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    expose:
      - "8080"
    volumes:
      - /opt/semiphemeral/data/web:/var/web
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private

  dm_jobs:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_DM_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=1
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs1:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs1
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=3
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs2:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs2
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=4
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs3:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs3
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=5
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs4:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs4
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=6
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs5:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs5
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=7
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs6:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs6
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=8
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs7:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs7
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=9
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs8:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs8
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=10
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs9:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs9
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=11
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs10:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs10
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=12
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs11:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs11
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=13
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs12:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs12
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=14
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs13:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs13
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=15
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs14:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs14
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=16
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs15:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs15
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=17
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs16:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs16
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=18
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs17:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs15
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=19
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs18:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs15
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=20
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs19:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs19
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=21
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs20:
    restart: always
    build: "src"
    environment:
      - CONTAINER_NAME=jobs15
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=22
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - web

  proxy:
    restart: always
    build: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/{{ domain }}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{ domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /opt/semiphemeral/data/proxy:/var/log/nginx
    networks:
      - default
    depends_on:
      - web

networks:
  default:
    driver: bridge
  host_private:
    driver: bridge
    internal: true
