version: "3"
services:
  redis:
    image: redis:alpine
    command: [ "redis-server", "--save", "3600", "10" ]
    volumes:
      - /opt/semiphemeral/data/redis:/data

  web:
    restart: always
    build: "src"
    environment:
      - REDIS_URL=redis://redis:6379
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_SEMIPHEMERAL_ACCESS_TOKEN={{ twitter_semiphemeral_access_token }}
      - TWITTER_SEMIPHEMERAL_ACCESS_KEY_KEY={{ twitter_semiphemeral_access_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - DATABASE_URI=postgresql://{{ postgres_user }}:{{ postgres_password }}@{{ db_private_ip }}:5432/{{ postgres_db }}
      - COOKIE_FERNET_KEY={{ cookie_fernet_key }}
      - STRIPE_PUBLISHABLE_KEY={{ stripe_publishable_key }}
      - STRIPE_SECRET_KEY={{ stripe_secret_key }}
      - MAINTENANCE_SECRET={{ maintenance_secret }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - DOMAIN={{ domain }}
    expose:
      - "8080"
    volumes:
      - /opt/semiphemeral/data/web:/var/web
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    networks:
      - default
      - host_private
    depends_on:
      - redis
      - monitor

  monitor:
    restart: "no"
    build: "src"
    environment:
      - REDIS_URL=redis://redis:6379
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_SEMIPHEMERAL_ACCESS_TOKEN={{ twitter_semiphemeral_access_token }}
      - TWITTER_SEMIPHEMERAL_ACCESS_KEY_KEY={{ twitter_semiphemeral_access_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - DATABASE_URI=postgresql://{{ postgres_user }}:{{ postgres_password }}@{{ db_private_ip }}:5432/{{ postgres_db }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    networks:
      - default
      - host_private
    ports:
      - "9181:9181"
    expose:
      - "9181"
    depends_on:
      - redis
    command:
      [
        "python",
        "-m",
        "poetry",
        "run",
        "python",
        "monitor.py"
      ]

  proxy:
    restart: always
    build: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/{{ domain }}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{ domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /opt/semiphemeral/data/proxy:/var/log/nginx
    networks:
      - default
    depends_on:
      - web

  worker:
    restart: always
    build: "src"
    environment:
      - REDIS_URL=redis://redis:6379
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_SEMIPHEMERAL_ACCESS_TOKEN={{ twitter_semiphemeral_access_token }}
      - TWITTER_SEMIPHEMERAL_ACCESS_KEY_KEY={{ twitter_semiphemeral_access_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - DATABASE_URI=postgresql://{{ postgres_user }}:{{ postgres_password }}@{{ db_private_ip }}:5432/{{ postgres_db }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    networks:
      - default
      - host_private
    deploy:
      replicas: 0
    volumes:
      - /opt/semiphemeral/data/bulk_dms:/var/bulk_dms
    depends_on:
      - redis
      - web
      - monitor
    command:
      [
        "python",
        "-m",
        "poetry",
        "run",
        "python",
        "worker.py"
      ]

  dms_worker:
    restart: always
    build: "src"
    environment:
      - REDIS_URL=redis://redis:6379
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_SEMIPHEMERAL_ACCESS_TOKEN={{ twitter_semiphemeral_access_token }}
      - TWITTER_SEMIPHEMERAL_ACCESS_KEY_KEY={{ twitter_semiphemeral_access_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - DATABASE_URI=postgresql://{{ postgres_user }}:{{ postgres_password }}@{{ db_private_ip }}:5432/{{ postgres_db }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    networks:
      - default
      - host_private
    depends_on:
      - redis
      - web
      - monitor
    command:
      [
        "python",
        "-m",
        "poetry",
        "run",
        "python",
        "worker.py",
        "--dms"
      ]

networks:
  default:
    driver: bridge
  host_private:
    driver: bridge
    internal: true
