version: '3'
services:

  web:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_WEB=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - DATABASE_URI={{ database_uri }}
      - COOKIE_FERNET_KEY={{ cookie_fernet_key }}
      - STRIPE_PUBLISHABLE_KEY={{ stripe_publishable_key }}
      - STRIPE_SECRET_KEY={{ stripe_secret_key }}
      - MAINTENANCE_SECRET={{ maintenance_secret }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    expose:
      - "8080"
    volumes:
      - /opt/semiphemeral/data/web:/var/web
    networks:
      - default
      - host_private

  dm_jobs:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_DM_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    networks:
      - default
      - host_private
    depends_on:
      - web
    
  export_jobs:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_EXPORT_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
    volumes:
      - /opt/semiphemeral/data/export:/export
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs1:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=10
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs2:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=20
    networks:
      - default
      - host_private
    depends_on:
      - web

  jobs3:
    restart: always
    build: "src"
    environment:
      - SEMIPHEMERAL_JOBS=1
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - TWITTER_DM_CONSUMER_TOKEN={{ twitter_dm_consumer_token }}
      - TWITTER_DM_CONSUMER_KEY={{ twitter_dm_consumer_secret }}
      - TWITTER_DM_ACCESS_TOKEN={{ twitter_dm_access_token }}
      - TWITTER_DM_ACCESS_KEY={{ twitter_dm_access_secret }}
      - DATABASE_URI={{ database_uri }}
      - ADMIN_USERNAME={{ admin_username }}
      - ADMIN_WEBHOOK={{ admin_webhook }}
      - SECONDS_TO_SLEEP=30
    networks:
      - default
      - host_private
    depends_on:
      - web

  proxy:
    restart: always
    build: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/{{ domain }}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{ domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /opt/semiphemeral/data/proxy:/var/log/nginx
    networks:
      - default
    depends_on:
      - web

networks:
  default:
    driver: bridge
  host_private:
    driver: bridge
    internal: true
