version: '3'
services:

  web:
    build: "web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/{{ frontend_domain }}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{ frontend_domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /opt/app_data/web/logs:/var/log/nginx
    networks:
      - default

  frontend:
    build: "frontend"
    environment:
      - FRONTEND_DOMAIN={{ frontend_domain }}
      - BACKEND_DOMAIN={{ backend_domain }}
    ports:
      - "3000:3000"
    networks:
      - default

  backend:
    build: "backend"
    environment:
      - FRONTEND_DOMAIN={{ frontend_domain }}
      - BACKEND_DOMAIN={{ backend_domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
    ports:
      - "8080:8080"
    volumes:
      - /opt/app_data/backend:/var/backend
    networks:
      - default

  db:
    image: "postgres:12"
    networks:
      - default

networks:
  default:
    driver: bridge
