version: '3'
services:

  proxy:
    restart: always
    build: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/{{ domain }}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{ domain }}/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /opt/semiphemeral/data/proxy:/var/log/nginx
    networks:
      - default

  web:
    restart: always
    build: "web"
    environment:
      - DEPLOY_ENVIRONMENT={{ deploy_environment }}
      - DOMAIN={{ domain }}
      - TWITTER_CONSUMER_TOKEN={{ twitter_consumer_token }}
      - TWITTER_CONSUMER_KEY={{ twitter_consumer_secret }}
      - DATABASE_URI={{ database_uri }}
      - COOKIE_FERNET_KEY={{ cookie_fernet_key }}
      - STRIPE_PUBLISHABLE_KEY={{ stripe_publishable_key }}
      - STRIPE_SECRET_KEY={{ stripe_secret_key }}
      - MAINTENANCE_SECRET={{ maintenance_secret }}
    expose:
      - "8080"
    volumes:
      - /opt/semiphemeral/data/web:/var/web
    networks:
      - default
      - host_private

networks:
  default:
    driver: bridge
  host_private:
    driver: bridge
    internal: true
