---
- name: set hostname
  hostname:
    name: "app-{{ deploy_environment }}"

- name: ensure dependencies are installed
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - certbot

- name: ensure semiphemeral directory exists
  file:
    path: /opt/semiphemeral
    state: directory

- name: /opt/semiphemeral/backup.sh template
  template:
    src: ../templates/opt/semiphemeral/backup.sh
    dest: /opt/semiphemeral/backup.sh
    owner: "root"
    mode: 0700

- name: /opt/semiphemeral/restore.sh template
  template:
    src: ../templates/opt/semiphemeral/restore.sh
    dest: /opt/semiphemeral/restore.sh
    owner: "root"
    mode: 0700

- name: ensure web volume directory has the right permissions
  file:
    path: /opt/semiphemeral/data/web
    state: directory
    owner: "1000"
    mode: 0700

- name: ensure redis volume directory has the right permissions
  file:
    path: /opt/semiphemeral/data/redis
    state: directory
    owner: "999"
    group: "1000"
    mode: 0700

- name: ensure bulk_dms volume directory has the right permissions
  file:
    path: /opt/semiphemeral/data/bulk_dms
    state: directory
    owner: "1000"
    mode: 0700

- name: ensure proxy volume data directory has the right permissions
  file:
    path: /opt/semiphemeral/data/proxy
    state: directory
    owner: "101" # nginx user
    mode: 0700

- name: /etc/logrotate.d/semiphemeral template
  template:
    src: ../templates/etc/logrotate.d/semiphemeral
    dest: /etc/logrotate.d/semiphemeral

- name: ensure we have a Let's Encrypt certificate (production)
  shell: certbot certonly --standalone -n --agree-tos --email micah@micahflee.com -d {{ domain }}

- name: ensure vm.overcommit_memory = 1 is set
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present

- name: ensure crons are enabled to automatically cleanup database
  cron:
    name: "cleanup users and DMs"
    minute: "30"
    hour: "4"
    job: docker exec -it app_worker_1 poetry run python tasks.py cleanup-users && docker exec -it app_jobs_1 poetry run python tasks.py cleanup-dm-jobs
