[tool.poetry]
name = "semiphemeral.com"
version = "0.1.0"
description = ""
authors = ["Micah Lee <micah@micahflee.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.6.2"
aiohttp-jinja2 = "^1.2.0"
tweepy = "^3.9.0"
gino = "^1.0.1"
aiopg = "^1.0.0"
sqlalchemy = "^1.3.19"
alembic = "^1.4.2"
jinja2 = "^2.11.2"
stripe = "^2.50.0"
requests = "^2.24.0"
selenium = "^3.141.0"
aiohttp_session = "^2.9.0"
cryptography = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
