[tool.poetry]
authors = ["Micah Lee <micah@micahflee.com>"]
description = ""
name = "semiphemeral.com"
version = "0.1.0"

[tool.poetry.dependencies]
aiohttp = "*"
aiohttp-jinja2 = "*"
aiohttp_session = "*"
aiopg = "*"
alembic = "*"
cryptography = "*"
gino = "*"
jinja2 = "*"
peony-twitter = {version = "*", extras = ["all"]}
python = "^3.10"
requests = "*"
sqlalchemy = ">=1.3,<1.4"
stripe = "*"
click = "*"
redis = "^4.2.2"
rq = "^1.10.1"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.1.13"]
