version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER={{ postgres_user }}
      - POSTGRES_PASSWORD={{ postgres_password }}
      - POSTGRES_DB={{ postgres_db }}
    volumes:
      - /db/mnt/data:/var/lib/postgresql/data
    ports:
      - '{{ db_private_ip }}:5432:5432'
