version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER={{ postgres_user }}
      - POSTGRES_PASSWORD={{ postgres_password }}
      - POSTGRES_DB={{ postgres_db }}
    volumes:
      - /db/mnt/data:/var/lib/postgresql/data
      - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    ports:
      - '{{ db_private_ip }}:5432:5432'
