---
- name: ensure dependencies are installed
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: ensure docker apt key is added
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker apt repository is installed
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: ensure docker is installed
  apt:
    force_apt_get: yes
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - python3-pip

- name: ensure docker python module is installed
  shell: pip3 install --upgrade pyyaml docker docker-compose
